### ISSUE TITLE
R4 SDHC DUAL CORE 2017 .COM.CN 

### ISSUE THREAD

**Issue by agen4er** [ntrteam/flashcart_core#108] opened 2017-11-21 13:38 UTC
ChipID: 
HW Revision: 

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

</p></details> 

GM9 Untrimmed Dump:

**Comment by angelsl** [comment] 2017-11-21 14:44
Dupe of #101

**Closed by angelsl** 2017-11-21 14:44 UTC

**Comment by trbocode** [comment] 2017-11-21 21:18
@angelsl #101 is actually a dupe of #33 . Both carts are the same, I confirmed it (My .com.cn card has an Ace3DS chipID).

**Comment by angelsl** [comment] 2017-11-22 07:04
@trbocode

Oh right, I forgot. Thanks.
