### ISSUE TITLE
R4 SDHC Dual-Core (www.r4isdhc.in)

### ISSUE THREAD

**Issue by yva96** [ntrteam/flashcart_core#103] opened 2017-10-27 15:21 UTC
ChipID: 00002FC
HW Revision: 2A2A2A2A

Software http://web.archive.org/web/20170129033344/http://www.r4isdhc.in:80/download_white_new2013/R4isdhc-White1.62.rar

Firmware upgrade file http://web.archive.org/web/20170129033344/http://www.r4isdhc.in:80/download_white_new2013/fwUpdate2013_V7.00.rar

Rom [AL3Y78_00.zip](https://github.com/ntrteam/flashcart_core/files/1425188/AL3Y78_00.zip)

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![r4i_r2_c42013new](https://user-images.githubusercontent.com/33157997/32111331-7d483e90-bb3a-11e7-8a6b-e7fb8807e485.jpg)
![images](https://user-images.githubusercontent.com/33157997/32111341-85bbe644-bb3a-11e7-848a-6a9f82ee83a9.jpg)
![img_20171027_172528](https://user-images.githubusercontent.com/33157997/32111873-125f4f90-bb3c-11e7-8585-3a55867e9fcf.jpg)
![img_20171027_172602](https://user-images.githubusercontent.com/33157997/32111875-128692da-bb3c-11e7-97a1-aba67156b586.jpg)

**Comment by yva96** [comment] 2017-10-30 07:58
ChipID: 00000FC2

**Comment by dark-samus** [comment] 2017-11-19 20:40
duplicate of #3 
closing.

**Closed by dark-samus** 2017-11-19 20:40 UTC
Labels: support request
