### ISSUE TITLE
R4iSDHC.hk R4 dual core

### ISSUE THREAD

**Issue by Juanito9001** [ntrteam/flashcart_core#20] opened 2017-08-22 14:42 UTC
Ok people...i dont know if this card was posted before to discussion... but i was Reading outside this posts, and some people says this card is more or less the same as R4 3ds gold (one of the compatibles with ntrboot) so my question is... is that true?? 
Oh... and the firmware of this card can be downloaded... or maybe "extracting" the ROM with GM9

ChipID:00000FC2
HWrev:FFFFFFFF
https://web.archive.org/web/20161113005731/http://www.r4isdhc.hk/download_2014/3DSV7.0.0-13%20upgarde%20firmware.rar
Thats the link to download the firmware (not kernel) in wayback machine
Btw... is a .nds file

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hedgeberg** [comment] 2017-08-22 15:50
Please read the readme. There is already work being done on this card. Please stop trying to send .nds files to us, those are the commerical rom and are not helpful. Please provide the requested info, i.e. pictures of the board and reseller link, or else this is not helpful.

**Comment by yacepi15** [comment] 2017-08-22 20:29
Hedgeberg... I want to ask you... What R4 SDHC DC is being worked? The .hk? The .com? What year?

Thank you.

**Comment by hedgeberg** [comment] 2017-08-22 21:07
Im not 100% sure, @dark-samus would be the one to ask about that.

**Comment by Juanito9001** [comment] 2017-08-23 18:42
[ROMS r4isdhc.hk.zip](https://github.com/kitling/flashcart_core/files/1246627/ROMS.r4isdhc.hk.zip)

Extracted with GM9 (trim and not trim)
i hope this will be of utility

**Comment by tamamushiiro** [comment] 2017-08-29 14:05
@dark-samus Is the R4 SDHC Dual Core card being worked on the one from r4isdhc.com, or r4isdhc.hk? Thanks for all your work.

**Comment by SamTorr** [comment] 2017-09-19 14:08
@dark-samus Is the R4 SDHC Dual Core card being worked on the one from r4isdhc.com, or r4isdhc.hk? Thanks for all your work.

**Comment by benji200** [comment] 2017-10-16 23:51
My r4 dual core 2013 with the page in www.r4isdhc.hk dont work with ntrboot, their characteristics are:
windbond
25Q16BVSIG1236
-----------
PD910B
1304
-----------
203K
KR465
i dont have the chip id and hw version
sorry for my bad english, im from to mexico and no speak english xd
![22554465_125084551528023_484027257_n](https://user-images.githubusercontent.com/32855107/31640266-0a6050a6-b2a3-11e7-9d18-b9ad60cd0d61.jpg)

**Comment by benji200** [comment] 2017-10-16 23:53
this page has the last kernel and firmware that came out for that card (r4i sdhc 2013 dualcore)
http://web.archive.org/web/20140701221531/http://www.r4isdhc.hk/r4-download/

**Comment by EleventhSign** [comment] 2017-10-17 00:13
@benji200 Yours is the original r4 dual core by r4isdhc.com (which later on continued to be sold by r4isdhc.hk). This isn't compatible yet with ntrboot_flasher.

**Comment by benji200** [comment] 2017-10-17 00:21
In the future maybe it can work?
I'll buy another flashcard in any case
Thanks

**Comment by Juanito9001** [comment] 2017-10-19 20:15
maybe... only the time can tell that, btw, with the actual version the flashcart is detected like a R4 dual core... but at the moment of dump, the program totally freezes

**Comment by dark-samus** [comment] 2017-11-23 21:38
Closing this one. It's a duplicate of #3

**Closed by dark-samus** 2017-11-23 21:38 UTC
Labels: support request

**Comment by Aaliq** [comment] 2022-11-08 08:56
> My r4 dual core 2013 with the page in www.r4isdhc.hk dont work with ntrboot, their characteristics are:
> windbond
> 25Q16BVSIG1236
> -----------
> PD910B
> 1304
> -----------
> 203K
> KR465
> i dont have the chip id and hw version
> sorry for my bad english, im from to mexico and no speak english xd
> ![22554465_125084551528023_484027257_n](https://user-images.githubusercontent.com/32855107/31640266-0a6050a6-b2a3-11e7-9d18-b9ad60cd0d61.jpg)
> 

Hi, I have the same cart! But it doesn't seem to work on my DSi. It just shows Menu? When i try. Could you please please please help me get this to work.. i know i don't need flashcart on a dsi and I can us the sd card. But I just need this to work..
